# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlexaNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AlexaNative

  target 'AlexaNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'